<?php
include "db_userdata_connect.php";
include "mail_connect.php";

if(isset($_POST['userID'])){
	$row = $usersqli->query("SELECT user_name, email, first_name, last_name FROM data WHERE userID=".$_POST['userID'])->fetch_assoc();
}else if(isset($_POST['user'])){
	$row = $usersqli->query("SELECT user_name, email, first_name, last_name FROM data WHERE user_name='".$_POST['user']."'")->fetch_assoc();
}

$user = $row['user_name'];
$user_name = $user;
$email = $row['email'];
$first_name = $row['first_name'];
$last_name = $row['last_name'];
$name = $first_name . " " . $last_name;

$hashed_user = password_hash($user, PASSWORD_DEFAULT);
$link = "https://www.gotonality.com/password-reset?hu=".$hashed_user;


$email_body = '<!doctype html> <html> <head><meta charset="utf-8"><style amp4email-boilerplate>body{visibility:hidden}</style><script async src="https://cdn.ampproject.org/v0.js"></script> <style amp-custom>
	 a[x-apple-data-detectors] { 	color:inherit; 	text-decoration:none; 	font-size:inherit; 	font-family:inherit; 	font-weight:inherit; 	line-height:inherit; } .es-desk-hidden { 	display:none; 	float:left; 	overflow:hidden; 	width:0; 	max-height:0; 	line-height:0; } .es-button-border:hover { 	border-style:solid solid solid solid; 	background:#0B317E; 	border-color:#42D159 #42D159 #42D159 #42D159; } s { 	text-decoration:line-through; } body { 	width:100%; 	font-family:roboto, "helvetica neue", helvetica, arial, sans-serif; } table { 	border-collapse:collapse; 	border-spacing:0px; } table td, html, body, .es-wrapper { 	padding:0; 	Margin:0; } .es-content, .es-header, .es-footer { 	table-layout:fixed; 	width:100%; } p, hr { 	Margin:0; } h1, h2, h3, h4, h5 { 	Margin:0; 	line-height:120%; 	font-family:roboto, "helvetica neue", helvetica, arial, sans-serif; } .es-left { 	float:left; } .es-right { 	float:right; } .es-p5 { 	padding:5px; } .es-p5t 
	{ 	padding-top:5px; } .es-p5b { 	padding-bottom:5px; } .es-p5l { 	padding-left:5px; } .es-p5r { 	padding-right:5px; } .es-p10 { 	padding:10px; } .es-p10t { 	padding-top:10px; } .es-p10b { 	padding-bottom:10px; } .es-p10l { 	padding-left:10px; } .es-p10r { 	padding-right:10px; } .es-p15 { 	padding:15px; } .es-p15t { 	padding-top:15px; } .es-p15b { 	padding-bottom:15px; } .es-p15l { 	padding-left:15px; } .es-p15r { 	padding-right:15px; } .es-p20 { 	padding:20px; } .es-p20t { 	padding-top:20px; } .es-p20b { 	padding-bottom:20px; } .es-p20l { 	padding-left:20px; } .es-p20r { 	padding-right:20px; } .es-p25 { 	padding:25px; } .es-p25t { 	padding-top:25px; } .es-p25b { 	padding-bottom:25px; } .es-p25l { 	padding-left:25px; } .es-p25r { 	padding-right:25px; } .es-p30 { 	padding:30px; } .es-p30t { 	padding-top:30px; } .es-p30b { 	padding-bottom:30px; } .es-p30l { 	padding-left:30px; } .es-p30r { 	padding-right:30px; } .es-p35 { 	padding:35px; 
	} .es-p35t { 	padding-top:35px; } .es-p35b { 	padding-bottom:35px; } .es-p35l { 	padding-left:35px; } .es-p35r { 	padding-right:35px; } .es-p40 { 	padding:40px; } .es-p40t { 	padding-top:40px; } .es-p40b { 	padding-bottom:40px; } .es-p40l { 	padding-left:40px; } .es-p40r { 	padding-right:40px; } .es-menu td { 	border:0; } a { 	font-family:roboto, "helvetica neue", helvetica, arial, sans-serif; 	font-size:16px; 	text-decoration:underline; } h1 { 	font-size:30px; 	font-style:normal; 	font-weight:bold; 	color:#212121; } h1 a { 	font-size:30px; } h2 { 	font-size:24px; 	font-style:normal; 	font-weight:bold; 	color:#212121; } h2 a { 	font-size:24px; } h3 { 	font-size:20px; 	font-style:normal; 	font-weight:normal; 	color:#212121; } h3 a { 	font-size:20px; } p, ul li, ol li { 	font-size:16px; 	font-family:roboto, "helvetica neue", helvetica, arial, sans-serif; 	line-height:150%; } ul li, ol li { 	Margin-bottom:15px; } .es-menu td a { 
		text-decoration:none; 	display:block; } .es-menu amp-img, .es-button amp-img { 	vertical-align:middle; } .es-wrapper { 	width:100%; 	height:100%; } .es-wrapper-color { 	background-color:#F8F9FD; } .es-content-body { 	background-color:transparent; } .es-content-body p, .es-content-body ul li, .es-content-body ol li { 	color:#131313; } .es-content-body a { 	color:#2CB543; } .es-header { 	background-color:transparent; } .es-header-body { 	background-color:#FFFFFF; } .es-header-body p, .es-header-body ul li, .es-header-body ol li { 	color:#333333; 	font-size:14px; } .es-header-body a { 	color:#1376C8; 	font-size:14px; } .es-footer { 	background-color:#F6F6F6; } .es-footer-body { 	background-color:transparent; } .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li { 	color:#131313; 	font-size:16px; } .es-footer-body a { 	color:#FFFFFF; 	font-size:16px; } .es-infoblock, .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li { 
		line-height:120%; 	font-size:12px; 	color:#FFFFFF; } .es-infoblock a { 	font-size:12px; 	color:#FFFFFF; } .es-button-border { 	border-style:solid solid solid solid; 	border-color:#2CB543 #2CB543 #2CB543 #2CB543; 	background:#071F4F; 	border-width:0px 0px 0px 0px; 	display:inline-block; 	border-radius:5px; 	width:auto; } .es-button img { 	display:inline-block; 	vertical-align:middle; } .es-p-default { 	padding-top:20px; 	padding-right:20px; 	padding-bottom:0px; 	padding-left:20px; } .es-p-all-default { 	padding:0px; } a.es-button, button.es-button { 	border-style:solid; 	border-color:#071F4F; 	border-width:10px 20px 10px 20px; 	display:inline-block; 	background:#071F4F; 	border-radius:5px; 	font-size:16px; 	font-family:roboto, "helvetica neue", helvetica, arial, sans-serif; 	font-weight:normal; 	font-style:normal; 	line-height:120%; 	color:#FFFFFF; 	text-decoration:none; 	width:auto; 	text-align:center; } .es-button-border:hover 
	a.es-button, .es-button-border:hover button.es-button { 	background:#0B317E; 	border-color:#0B317E; } @media only screen and (max-width:600px) {.st-br { padding-left:10px; padding-right:10px } p, ul li, ol li, a { font-size:16px; line-height:150% } h1 { font-size:30px; text-align:center; line-height:120% } h2 { font-size:26px; text-align:center; line-height:120% } h3 { font-size:20px; text-align:center; line-height:120% } h1 a { font-size:30px; text-align:center } h2 a { font-size:26px; text-align:center } h3 a { font-size:20px; text-align:center } .es-menu td a { font-size:14px } .es-header-body p, .es-header-body ul li, .es-header-body ol li, .es-header-body a { font-size:16px } .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li, .es-footer-body a { font-size:14px } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock a { font-size:12px } *[class="gmail-fix"] { display:none } .es-m-txt-c, .es-m-txt-c 
	h1, .es-m-txt-c h2, .es-m-txt-c h3 { text-align:center } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 { text-align:right } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3 { text-align:left } .es-m-txt-r amp-img { float:right } .es-m-txt-c amp-img { margin:0 auto } .es-m-txt-l amp-img { float:left } .es-button-border { display:block } .es-btn-fw { border-width:10px 0px; text-align:center } .es-adaptive table, .es-btn-fw, .es-btn-fw-brdr, .es-left, .es-right { width:100% } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%; max-width:600px } .es-adapt-td { display:block; width:100% } .adapt-img { width:100%; height:auto } td.es-m-p0 { padding:0 } td.es-m-p0r { padding-right:0 } td.es-m-p0l { padding-left:0 } td.es-m-p0t { padding-top:0 } td.es-m-p0b { padding-bottom:0 } td.es-m-p20b { padding-bottom:20px } .es-mobile-hidden, .es-hidden { display:none } 
	tr.es-desk-hidden, td.es-desk-hidden, table.es-desk-hidden { width:auto; overflow:visible; float:none; max-height:inherit; line-height:inherit } tr.es-desk-hidden { display:table-row } table.es-desk-hidden { display:table } td.es-desk-menu-hidden { display:table-cell } table.es-table-not-adapt, .esd-block-html table { width:auto } table.es-social { display:inline-block } table.es-social td { display:inline-block } td.es-m-p5 { padding:5px } td.es-m-p5t { padding-top:5px } td.es-m-p5b { padding-bottom:5px } td.es-m-p5r { padding-right:5px } td.es-m-p5l { padding-left:5px } td.es-m-p10 { padding:10px } td.es-m-p10t { padding-top:10px } td.es-m-p10b { padding-bottom:10px } td.es-m-p10r { padding-right:10px } td.es-m-p10l { padding-left:10px } td.es-m-p15 { padding:15px } td.es-m-p15t { padding-top:15px } td.es-m-p15b { padding-bottom:15px } td.es-m-p15r { padding-right:15px } td.es-m-p15l { padding-left:15px } td.es-m-p20 { padding:20px 
	} td.es-m-p20t { padding-top:20px } td.es-m-p20r { padding-right:20px } td.es-m-p20l { padding-left:20px } td.es-m-p25 { padding:25px } td.es-m-p25t { padding-top:25px } td.es-m-p25b { padding-bottom:25px } td.es-m-p25r { padding-right:25px } td.es-m-p25l { padding-left:25px } td.es-m-p30 { padding:30px } td.es-m-p30t { padding-top:30px } td.es-m-p30b { padding-bottom:30px } td.es-m-p30r { padding-right:30px } td.es-m-p30l { padding-left:30px } td.es-m-p35 { padding:35px } td.es-m-p35t { padding-top:35px } td.es-m-p35b { padding-bottom:35px } td.es-m-p35r { padding-right:35px } td.es-m-p35l { padding-left:35px } td.es-m-p40 { padding:40px } td.es-m-p40t { padding-top:40px } td.es-m-p40b { padding-bottom:40px } td.es-m-p40r { padding-right:40px } td.es-m-p40l { padding-left:40px } a.es-button, button.es-button { font-size:16px; display:block; border-left-width:0px; border-right-width:0px } } </style> </head> <body>
	 <div class="es-wrapper-color"> <!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#f8f9fd"></v:fill> </v:background><![endif]--> <table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0"> <tr> <td valign="top"> <table cellpadding="0" cellspacing="0" class="es-content" align="center"> <tr> <td align="center" bgcolor="#f8f9fd" style="background-color: #f8f9fd"> <table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600"> <tr> <td class="es-p10t es-p15b es-p30r es-p30l" align="left"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td width="540" align="center" valign="top"> <table cellpadding="0" cellspacing="0" width="100%" role="presentation"> <tr> <td align="center" style="font-size: 0px">
	<amp-img src="https://imgur.com/dS3TIf9.png" alt style="display: block" width="130" height="123"></amp-img></td> </tr> </table></td> </tr> </table></td> </tr> </table></td> </tr> </table> <table cellpadding="0" cellspacing="0" class="es-content" align="center"> <tr> <td align="center" bgcolor="#f8f9fd" style="background-color: #f8f9fd"> <table bgcolor="transparent" class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600" style="background-color: transparent"> <tr> <td class="es-p20t es-p10b es-p20r es-p20l" align="left"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td width="560" align="center" valign="top"> <table cellpadding="0" cellspacing="0" width="100%" role="presentation"> <tr> <td align="center" class="es-p10b"><h1>Tonality password reset</h1></td> </tr> <tr>
	 <td align="center" class="es-p10t es-p10b"><p>You have requested to reset your Tonality password</p></td> </tr> </table></td> </tr> </table></td> </tr> <tr> <td class="es-p15t es-m-p15t es-m-p0b es-m-p0r es-m-p0l" align="left"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td width="600" align="center" valign="top"> <table cellpadding="0" cellspacing="0" width="100%" role="presentation"> <tr> <td align="center" style="font-size: 0px"><amp-img class="adapt-img" src="https://imgur.com/ENjChsd.png" alt style="display: block" width="600" height="150" layout="responsive"></amp-img></td> </tr> </table></td> </tr> </table></td> </tr> </table></td> </tr> </table> <table cellpadding="0" cellspacing="0" class="es-content" align="center"> <tr>
	 <td align="center" bgcolor="#071f4f" style="background-color: #071f4f;background-image: url(https://nzhnlu.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/10801592857268437.png);background-repeat: no-repeat;background-position: center top"> <table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600"> <tr> <td class="es-p40t es-p40b es-p30r es-p30l" align="left"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td width="540" align="center" valign="top"> <table cellpadding="0" cellspacing="0" width="100%" role="presentation"> <tr> <td align="center" height="20"></td> </tr> <tr> <td align="left" class="es-p10b"><h2 style="text-align: center;color: #ffffff">Didn\'t reset your password?</h2></td> </tr> <tr> <td align="center" class="es-p10t es-p10b"><p style="color: #ffffff">
	No problem. You can disregard this email.</p></td> </tr> </table></td> </tr> </table></td> </tr> </table></td> </tr> </table> <table cellpadding="0" cellspacing="0" class="es-content" align="center"> <tr> <td align="center" bgcolor="#f8f9fd" style="background-color: #f8f9fd;background-image: url(https://nzhnlu.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/83191592482092483.png);background-repeat: no-repeat;background-position: center center"> <table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600"> <tr> <td class="es-p40t es-p15b es-p20r es-p20l" align="left"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td width="281" align="center" valign="top"> <table cellpadding="0" cellspacing="0" width="100%" role="presentation"> <tr> <td align="left"><h1 style="text-align: center">
	Reset Password</h1></td> </tr> <tr> <td align="center" class="es-m-txt-c es-p15t"><p style="font-size: 16px">Follow the link to reset your password</p></td> </tr> </table></td> </tr> </table></td> </tr> <tr> <td class="es-p20t es-p20r es-p20l" align="left"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td width="560" align="center" valign="top"> <table cellpadding="0" cellspacing="0" width="100%" role="presentation"> <tr> <td align="center" class="es-m-txt-c es-p15t"><p style="font-size: 16px"><a href="'.$link.'">Reset Password</a><br><br><br>If you have any problems, you can contact us <a href="https://gotonality.com/contact">here</a></p></td> </tr> <tr> <td align="center" class="es-p20" style="font-size:0"> <table border="0" width="100%" cellpadding="0" cellspacing="0" role="presentation"> <tr> <td style="border-bottom: 1px solid #cccccc;background:none;height:1px;width:100%;margin:0px 0px 0px 0px"></td> </tr> </table></td> </tr> </table></td>
	 </tr> </table></td> </tr> </table></td> </tr> </table> <table cellpadding="0" cellspacing="0" class="es-content" align="center"> <tr> <td align="center" bgcolor="#0a2b6e" style="background-color: #0a2b6e;background-image: url(https://nzhnlu.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/33971592408649468.png);background-repeat: no-repeat;background-position: center center"> <table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600"> <tr> <td class="es-p40t es-p40b es-m-p40t es-m-p40b es-m-p20r es-m-p20l" align="left"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td width="600" align="center" valign="top"> <table cellpadding="0" cellspacing="0" width="100%" bgcolor="#f0f3fe" style="background-color: #f0f3fe;border-radius: 20px;border-collapse: separate" role="presentation"> <tr> <td align="left" class="es-p25t es-p10b es-p20r es-p20l">
	<h1 style="text-align: center;line-height: 150%">Get back to Tonality now!</h1></td> </tr> <tr> <td align="center" class="es-p10t es-p25b es-p20r es-p20l es-m-p15t es-m-p20b es-m-p20r es-m-p20l"><span class="es-button-border"><a href="https://gotonality.com/index" class="es-button" target="_blank" style="border-width: 10px 20px">Go Now!<!--[if !mso]><!-- --><amp-img src="https://nzhnlu.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/32371592816290258.png" alt="icon" width="16" style="margin-left:10px" height="11"></amp-img> <!--<![endif]--></a></span></td> </tr> </table></td> </tr> </table></td> </tr> </table></td> </tr> </table></td> </tr> </table> </div> </body>
	</html>
	';

$mail->isSMTP();
$mail->SMTPDebug = 0;
$mail->Debugoutput = 'html';
$mail->Host = 'mail.gotonality.com;';
$mail->SMTPAuth = true;
$mail->Username = 'no-reply@gotonality.com';
$mail->Password = 'VRSPassword1!';
$mail->SMTPSecure = 'ssl';
$mail->Port = 290;

$mail->setFrom('no-reply@gotonality.com', 'Tonality');
$mail->addAddress($email, $name);

$mail->isHTML(true);                                  // Set email format to HTML
$mail->CharSet = 'UTF-8';
$mail->Encoding = 'base64';
$mail->Subject = 'Tonality Password Reset';
$mail->Body    = $email_body;
$mail->AltBody = 'Use this link to reset your password: '.$link;

$mail->send();  

header('Location: /login?message=reset');

?>